### ISSUE TITLE
Running with more arguments than just size results in error.

### ISSUE THREAD

**Issue by kruug** [jonhnet/maze-harvester#1]
`gradlew run --args='--size=30,30 --paper=letter'` results in "Unknown command-line option '--paper'."

**Comment by kruug** [comment]
Well, this was a reading comprehension issue.  Only `size` gets the `=`.  Other arguments do not require the `=`.

**Comment by jonhnet** [comment]
Actually, either syntax should work. I just tested with a fresh clone, and both do work. ? Anyway, hope you're enjoying your mazes.

**Comment by markusgritsch** [comment]
FYI: On the Windows command line I had to change ' to " to get it working.

Are double quotes working for the bash too? If so, maybe the examples in the documentation should be changed.
