### ISSUE TITLE
Update to new OS and Inkscape

### ISSUE THREAD

**Issue by prkos** [jonhnet/maze-harvester#2]
I can't get this extension to work on Ubuntu 20.04 and Inkscape 1.0.

It would be nice to have it working :)

**Comment by jonhnet** [comment]
Hi Mihaela, 

Send me a pull request! 

   --Jon 

On 2020-10-29 17:45, Mihaela Jurković wrote:

> I can't get this extension to work on Ubuntu 20.04 and Inkscape 1.0. 
> 
> It would be nice to have it working :) 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1] https://github.com/jonhnet/maze-harvester/issues/2
[2]

**Comment by prkos** [comment]
Is it a simple version change fix? I'm not a programmer so my abilities here are limited.

**Comment by jonhnet** [comment]
Ah, gotcha. I'll have to try it on a matching machine and see what happens. Haven't run it for a couple months on my own laptop.On Nov 1, 2020 18:42, Mihaela Jurković <notifications@github.com> wrote:
Is it a simple version change fix? I'm not a programmer so my abilities here are limited.

**Comment by jonhnet** [comment]
Hmm, my machine is running 20.04, but I have inkscape 0.92.5. How did you get sweet 1.0 goodness on your machine? Did you upgrade inkscape via PPA?

**Comment by prkos** [comment]
I don't seem to have the Inkscape PPA active so I'm confused, I don't think I compiled it from source. I probably got help from the chat and forgot the steps: https://chat.inkscape.org/home

But I also tried the Appimage and it's working perfectly, it's the first option here: https://inkscape.org/release/1.0.1/gnulinux/

I'm using the Appimage one when I need to import PDFs, apparently there are some lib dependency mismatch with the version I have installed for the PDF importer to work properly.

**Comment by jonhnet** [comment]
Okay, fixed the docs. Use "-o" in lieu of "-z -e" as the README has previously advised.

Sorry that took so long. The ppa instructions were right there on the inkscape home page, once I bothered to look. :v)
