### ISSUE TITLE
Right border of hex maze

### ISSUE THREAD

**Issue by markusgritsch** [jonhnet/maze-harvester#3]
Hi Jon,

thanks for this amazing program! I have one question: When using --pattern hexagon, every row has the same number of columns. E.g. --size=4,5

![grafik](https://user-images.githubusercontent.com/2684183/99244493-72713700-2802-11eb-8659-2edfb19c0786.png)

Would it be possible to have a new option to get a hex maze like this:

![grafik](https://user-images.githubusercontent.com/2684183/99244855-f3c8c980-2802-11eb-96b1-fec0e0a61318.png)

**Comment by jonhnet** [comment]
Hmm, that shouldn't be super hard. Not sure when I'll have time to do it. In the meantime, you could try feeding it a mask image with a white stripe on the right side to knock out those cells...On Nov 16, 2020 02:58, markusgritsch <notifications@github.com> wrote:
Hi Jon,
thanks for this amazing program! I have one question: When using --pattern hexagon, every row has the same number of columns. E.g. --size=4,5

Would it be possible to have a new option to get a hex maze like this:

**Comment by markusgritsch** [comment]
Great, looking forward to it!

Knocking out those cells using a mask image unfortunately does not work, as it removes too much like reducing the horizontal size by one step.

**Comment by jonhnet** [comment]
okay, fixed.

**Comment by markusgritsch** [comment]
Wow, that was fast. Thanks a lot! Works great.
