### ISSUE TITLE
Paper size issue

### ISSUE THREAD

**Issue by markusgritsch** [jonhnet/maze-harvester#4]
When specifying the paper size using --paper, the resulting page size in Inkscape deviates a bit:

![grafik](https://user-images.githubusercontent.com/2684183/99301807-c6097200-284e-11eb-827d-af08a12d7b97.png)

**Comment by jonhnet** [comment]
Can you peek inside the SVG and see what's coming out of mazeharvester?

You might also try correcting the size in inkscape and saving it out as a fresh SVG, and seeing what that says.

I suspect I know what's going on. The difference is a ratio of 90:96. Inkscape changed its default DPI from 90 to 96. This error is surely related. Not sure how to fix it -- but looking at the SVG before and after is probably a good start.

**Comment by markusgritsch** [comment]
Thanks for the 90:96 hint. I just compensate by this factor when specifying --paper and all is well.

**Comment by jonhnet** [comment]
okay, using the power of grep, I found and fixed the dpi constant in my source code. :v) You should no longer need to manually compensate for the incorrect paper size.

**Comment by markusgritsch** [comment]
Nice. Maybe you want to fix another minor paper size issue:

![grafik](https://user-images.githubusercontent.com/2684183/100478659-25d40880-30ec-11eb-8759-8f9978d292df.png)

The `width` and `height` attributes of the `<svg>` tag seem to get truncated to integers. They should be the same as the ones of the `<rect>`.

To work around this I currently use the Inkscape `--export-area-drawing` option. Otherwise the exported image gets truncated a bit.

**Comment by jonhnet** [comment]
Tragically, this integer truncation is a limitation in the SVGGraphics2D library. It represents the SVG canvas size with a java.awt.Dimension, which uses an integer representation:

https://github.com/iconfinder/batik/blob/master/sources/org/apache/batik/svggen/SVGGraphics2D.java#L576

I fixed it with an elaborate workaround.

**Comment by markusgritsch** [comment]
Perfect!
