### ISSUE TITLE
Hex row count issue

### ISSUE THREAD

**Issue by markusgritsch** [jonhnet/maze-harvester#5]
When specifying small hex row counts, everything is fine:

--size=2,2
![grafik](https://user-images.githubusercontent.com/2684183/99493370-60f96d80-296f-11eb-91fe-75d109334b91.png)

--size=2,3
![grafik](https://user-images.githubusercontent.com/2684183/99493411-75d60100-296f-11eb-90be-b556dc516308.png)

This works fine up to 6 rows
--size=2,6
![grafik](https://user-images.githubusercontent.com/2684183/99493567-bdf52380-296f-11eb-901d-9a8b27d315ad.png)

but starting from 7 rows, an extra row gets added:
--size=2,7
![grafik](https://user-images.githubusercontent.com/2684183/99493655-e846e100-296f-11eb-9ef3-2466011c239e.png)

This additional row continues until --size=2,12
![grafik](https://user-images.githubusercontent.com/2684183/99493819-322fc700-2970-11eb-8f36-8b1a8fdabd47.png)

And starting from --size=2,13 two additional rows get added
![grafik](https://user-images.githubusercontent.com/2684183/99493881-4ffd2c00-2970-11eb-8807-9af5315c94f2.png)

Probably some issue related to the sqrt(3)/2 scaling of the grid in vertical direction due to its hex nature.

**Comment by jonhnet** [comment]
Hmm, that's by design -- although I acknowledge that maybe my design is a bug to you. :v)

The idea is that the --size w,h maintains aspect ratio in "paper units", so that if the paper size is proportional, the margins will be even all the way around. Likewise, if you're trying to generate the maze against a mask, --size is how you specify the "density" of the maze, but you probably want w,h to be proportional to the aspect ratio of the mask. In particular, when my kids demand a giant maze from the large-format pen plotter, I don't care *exactly* how many rows it has, I care about the overall paper size and then the approximate density of cells.

I don't have intuition for why you want precise control of the cell count, so I don't yet understand exactly what a better parameter interface would be.

**Comment by markusgritsch** [comment]
My intuition is to generate the backs of playing cards:
![grafik](https://user-images.githubusercontent.com/2684183/99577287-6ab8ba80-29db-11eb-8468-ba63284bc345.png)
To match the aspect ratio of the playing cards, it is desirable to be able to specify the exact cell count. In the horizontal direction it works fine, but vertically there is no way to specify 7 rows. Or 14. Or probably any multiple of 7.

Worse, since the placement of the exits seems to uses the same scaling algorithm, it's not possible to place the exits for some specific cells. I used this in the card design as the marking system, where one can tell the suit and rank of the card from looking at the back. I worked around this design issue, so you don't need to change it. Nevertheless, is there an easy way (like the previous change for the column count in HexFieldFactory.java) to change this by me locally?

![grafik](https://user-images.githubusercontent.com/2684183/99578468-2f1ef000-29dd-11eb-95de-ef8e8dbf820b.png)

**Comment by jonhnet** [comment]
Oooh, cool application!

Here's a hackaround for you to try: HexFieldFactory.java line 25, comment out "/ rh":
      (int) (fieldMask.getMaskSize().height  /* / rh */ ),

Does that give you the correct results?

I think it'll squish masks, so I'm not sure yet if I want to switch this around, but I'll think about it.

**Comment by markusgritsch** [comment]
Thanks, yes, this works for --size. Do you have a similar hint what to change for the --absoluteExits placement?

**Comment by jonhnet** [comment]
Okay, I just pushed changes that fix both of these issues. --size now means size by count of cells. Image masks get distorted for those patterns, which I solved with documentation. :v) absolute coordinates are also measured in cellspace now; I was able to place exits at each cell along the raggedy right edge of a 7x7 hex maze.

**Comment by jonhnet** [comment]
Might need a copy of that card deck when you print it, though...

**Comment by jelson** [comment]
@markusgritsch I'm curious, are you constructing a puzzle?

**Comment by markusgritsch** [comment]
No, it's a regular playing cards deck. The marking system on the back is used to identify the suit and rank of the card.

![fronts](https://user-images.githubusercontent.com/2684183/100057680-3bb1a700-2e28-11eb-93d5-0423f4467255.png)
![backs](https://user-images.githubusercontent.com/2684183/100057722-4d934a00-2e28-11eb-909e-ed6f60338f23.png)
![3](https://user-images.githubusercontent.com/2684183/100057738-56841b80-2e28-11eb-90a7-94d4742f2869.jpg)

**Comment by markusgritsch** [comment]
The design is now live and available here:
https://www.makeplayingcards.com/sell/marketplace/hexmaze-marked-playing-cards.html

**Comment by jelson** [comment]
That's really neat! I'm curious, where did you get the card faces from for the card fronts? I searched the web for a while last night but couldn't find artwork quite like the classic version you used.

**Comment by markusgritsch** [comment]
I bought the designs from "Black Roses Playing Cards" https://blackroses.cards/collections/downloads for €18.

You can also get the "Vector Playing Cards" https://totalnonsense.com/download/download-vector-playing-cards/ for free.
